# The URL the site will be built for
base_url = "https://crimsontome.com"

# Use terminal theme
theme = "terminimal"

# change output dir to _site
output_dir = "_site"

# autogen feed
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# switch accent colour from blue to pink - looks more like purple
accent_color = "pink"

# switch logo text from the default
logo_text = "CrimsonTome's Blog"

author = "CrimsonTome"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "Blog", url = "$BASE_URL"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
#    {name = "tags", url = "$BASE_URL/tags"},
    {name = "Archive", url = "$BASE_URL/archive"},
    {name = "About me", url = "$BASE_URL/about"},
    {name = "My stack", url= "$BASE_URL/stack"},    
    # set newtab to true to make the link open in new tab
    {name = "GitHub", url = "https://github.com/crimsontome", newtab = true},
]

#enable tags 
#taxonomies = [
#    {name = "tags"},
#]


#enable full unicode support
use_full_hack_font = true

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "static/favicon.ico"
# favicon_mimetype = "image/vnd.microsoft.icon"
page_titles = "combined"
